# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/victor/Documents/Cours/INSA Lyon - 4IF/GrammaireLangage/LutinLangInterperter"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/victor/Documents/Cours/INSA Lyon - 4IF/GrammaireLangage/LutinLangInterperter"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/victor/Documents/Cours/INSA Lyon - 4IF/GrammaireLangage/LutinLangInterperter/CMakeFiles" "/Users/victor/Documents/Cours/INSA Lyon - 4IF/GrammaireLangage/LutinLangInterperter/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/victor/Documents/Cours/INSA Lyon - 4IF/GrammaireLangage/LutinLangInterperter/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lut

# Build rule for target.
lut: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lut
.PHONY : lut

# fast build rule for target.
lut/fast:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/build
.PHONY : lut/fast

src/Automate.o: src/Automate.cpp.o

.PHONY : src/Automate.o

# target to build an object file
src/Automate.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Automate.cpp.o
.PHONY : src/Automate.cpp.o

src/Automate.i: src/Automate.cpp.i

.PHONY : src/Automate.i

# target to preprocess a source file
src/Automate.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Automate.cpp.i
.PHONY : src/Automate.cpp.i

src/Automate.s: src/Automate.cpp.s

.PHONY : src/Automate.s

# target to generate assembly for a file
src/Automate.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Automate.cpp.s
.PHONY : src/Automate.cpp.s

src/Automaton.o: src/Automaton.cpp.o

.PHONY : src/Automaton.o

# target to build an object file
src/Automaton.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Automaton.cpp.o
.PHONY : src/Automaton.cpp.o

src/Automaton.i: src/Automaton.cpp.i

.PHONY : src/Automaton.i

# target to preprocess a source file
src/Automaton.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Automaton.cpp.i
.PHONY : src/Automaton.cpp.i

src/Automaton.s: src/Automaton.cpp.s

.PHONY : src/Automaton.s

# target to generate assembly for a file
src/Automaton.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Automaton.cpp.s
.PHONY : src/Automaton.cpp.s

src/EtatN.o: src/EtatN.cpp.o

.PHONY : src/EtatN.o

# target to build an object file
src/EtatN.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/EtatN.cpp.o
.PHONY : src/EtatN.cpp.o

src/EtatN.i: src/EtatN.cpp.i

.PHONY : src/EtatN.i

# target to preprocess a source file
src/EtatN.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/EtatN.cpp.i
.PHONY : src/EtatN.cpp.i

src/EtatN.s: src/EtatN.cpp.s

.PHONY : src/EtatN.s

# target to generate assembly for a file
src/EtatN.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/EtatN.cpp.s
.PHONY : src/EtatN.cpp.s

src/Lexer.o: src/Lexer.cpp.o

.PHONY : src/Lexer.o

# target to build an object file
src/Lexer.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Lexer.cpp.o
.PHONY : src/Lexer.cpp.o

src/Lexer.i: src/Lexer.cpp.i

.PHONY : src/Lexer.i

# target to preprocess a source file
src/Lexer.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Lexer.cpp.i
.PHONY : src/Lexer.cpp.i

src/Lexer.s: src/Lexer.cpp.s

.PHONY : src/Lexer.s

# target to generate assembly for a file
src/Lexer.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Lexer.cpp.s
.PHONY : src/Lexer.cpp.s

src/lutin.o: src/lutin.cpp.o

.PHONY : src/lutin.o

# target to build an object file
src/lutin.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/lutin.cpp.o
.PHONY : src/lutin.cpp.o

src/lutin.i: src/lutin.cpp.i

.PHONY : src/lutin.i

# target to preprocess a source file
src/lutin.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/lutin.cpp.i
.PHONY : src/lutin.cpp.i

src/lutin.s: src/lutin.cpp.s

.PHONY : src/lutin.s

# target to generate assembly for a file
src/lutin.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/lutin.cpp.s
.PHONY : src/lutin.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lut"
	@echo "... src/Automate.o"
	@echo "... src/Automate.i"
	@echo "... src/Automate.s"
	@echo "... src/Automaton.o"
	@echo "... src/Automaton.i"
	@echo "... src/Automaton.s"
	@echo "... src/EtatN.o"
	@echo "... src/EtatN.i"
	@echo "... src/EtatN.s"
	@echo "... src/Lexer.o"
	@echo "... src/Lexer.i"
	@echo "... src/Lexer.s"
	@echo "... src/lutin.o"
	@echo "... src/lutin.i"
	@echo "... src/lutin.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

