# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/victor/Documents/Cours/INSA Lyon - 4IF/GrammaireLangage/LutinLangInterperter"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/victor/Documents/Cours/INSA Lyon - 4IF/GrammaireLangage/LutinLangInterperter"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/victor/Documents/Cours/INSA Lyon - 4IF/GrammaireLangage/LutinLangInterperter/CMakeFiles" "/Users/victor/Documents/Cours/INSA Lyon - 4IF/GrammaireLangage/LutinLangInterperter/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/victor/Documents/Cours/INSA Lyon - 4IF/GrammaireLangage/LutinLangInterperter/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lut

# Build rule for target.
lut: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lut
.PHONY : lut

# fast build rule for target.
lut/fast:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/build
.PHONY : lut/fast

src/Affectation.o: src/Affectation.cpp.o

.PHONY : src/Affectation.o

# target to build an object file
src/Affectation.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Affectation.cpp.o
.PHONY : src/Affectation.cpp.o

src/Affectation.i: src/Affectation.cpp.i

.PHONY : src/Affectation.i

# target to preprocess a source file
src/Affectation.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Affectation.cpp.i
.PHONY : src/Affectation.cpp.i

src/Affectation.s: src/Affectation.cpp.s

.PHONY : src/Affectation.s

# target to generate assembly for a file
src/Affectation.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Affectation.cpp.s
.PHONY : src/Affectation.cpp.s

src/Automaton.o: src/Automaton.cpp.o

.PHONY : src/Automaton.o

# target to build an object file
src/Automaton.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Automaton.cpp.o
.PHONY : src/Automaton.cpp.o

src/Automaton.i: src/Automaton.cpp.i

.PHONY : src/Automaton.i

# target to preprocess a source file
src/Automaton.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Automaton.cpp.i
.PHONY : src/Automaton.cpp.i

src/Automaton.s: src/Automaton.cpp.s

.PHONY : src/Automaton.s

# target to generate assembly for a file
src/Automaton.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Automaton.cpp.s
.PHONY : src/Automaton.cpp.s

src/DeclarationConst.o: src/DeclarationConst.cpp.o

.PHONY : src/DeclarationConst.o

# target to build an object file
src/DeclarationConst.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/DeclarationConst.cpp.o
.PHONY : src/DeclarationConst.cpp.o

src/DeclarationConst.i: src/DeclarationConst.cpp.i

.PHONY : src/DeclarationConst.i

# target to preprocess a source file
src/DeclarationConst.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/DeclarationConst.cpp.i
.PHONY : src/DeclarationConst.cpp.i

src/DeclarationConst.s: src/DeclarationConst.cpp.s

.PHONY : src/DeclarationConst.s

# target to generate assembly for a file
src/DeclarationConst.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/DeclarationConst.cpp.s
.PHONY : src/DeclarationConst.cpp.s

src/DeclarationVariable.o: src/DeclarationVariable.cpp.o

.PHONY : src/DeclarationVariable.o

# target to build an object file
src/DeclarationVariable.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/DeclarationVariable.cpp.o
.PHONY : src/DeclarationVariable.cpp.o

src/DeclarationVariable.i: src/DeclarationVariable.cpp.i

.PHONY : src/DeclarationVariable.i

# target to preprocess a source file
src/DeclarationVariable.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/DeclarationVariable.cpp.i
.PHONY : src/DeclarationVariable.cpp.i

src/DeclarationVariable.s: src/DeclarationVariable.cpp.s

.PHONY : src/DeclarationVariable.s

# target to generate assembly for a file
src/DeclarationVariable.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/DeclarationVariable.cpp.s
.PHONY : src/DeclarationVariable.cpp.s

src/Ecrire.o: src/Ecrire.cpp.o

.PHONY : src/Ecrire.o

# target to build an object file
src/Ecrire.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Ecrire.cpp.o
.PHONY : src/Ecrire.cpp.o

src/Ecrire.i: src/Ecrire.cpp.i

.PHONY : src/Ecrire.i

# target to preprocess a source file
src/Ecrire.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Ecrire.cpp.i
.PHONY : src/Ecrire.cpp.i

src/Ecrire.s: src/Ecrire.cpp.s

.PHONY : src/Ecrire.s

# target to generate assembly for a file
src/Ecrire.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Ecrire.cpp.s
.PHONY : src/Ecrire.cpp.s

src/Expression.o: src/Expression.cpp.o

.PHONY : src/Expression.o

# target to build an object file
src/Expression.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Expression.cpp.o
.PHONY : src/Expression.cpp.o

src/Expression.i: src/Expression.cpp.i

.PHONY : src/Expression.i

# target to preprocess a source file
src/Expression.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Expression.cpp.i
.PHONY : src/Expression.cpp.i

src/Expression.s: src/Expression.cpp.s

.PHONY : src/Expression.s

# target to generate assembly for a file
src/Expression.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Expression.cpp.s
.PHONY : src/Expression.cpp.s

src/Lexer.o: src/Lexer.cpp.o

.PHONY : src/Lexer.o

# target to build an object file
src/Lexer.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Lexer.cpp.o
.PHONY : src/Lexer.cpp.o

src/Lexer.i: src/Lexer.cpp.i

.PHONY : src/Lexer.i

# target to preprocess a source file
src/Lexer.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Lexer.cpp.i
.PHONY : src/Lexer.cpp.i

src/Lexer.s: src/Lexer.cpp.s

.PHONY : src/Lexer.s

# target to generate assembly for a file
src/Lexer.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Lexer.cpp.s
.PHONY : src/Lexer.cpp.s

src/Lire.o: src/Lire.cpp.o

.PHONY : src/Lire.o

# target to build an object file
src/Lire.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Lire.cpp.o
.PHONY : src/Lire.cpp.o

src/Lire.i: src/Lire.cpp.i

.PHONY : src/Lire.i

# target to preprocess a source file
src/Lire.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Lire.cpp.i
.PHONY : src/Lire.cpp.i

src/Lire.s: src/Lire.cpp.s

.PHONY : src/Lire.s

# target to generate assembly for a file
src/Lire.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Lire.cpp.s
.PHONY : src/Lire.cpp.s

src/PartieDeclarative.o: src/PartieDeclarative.cpp.o

.PHONY : src/PartieDeclarative.o

# target to build an object file
src/PartieDeclarative.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/PartieDeclarative.cpp.o
.PHONY : src/PartieDeclarative.cpp.o

src/PartieDeclarative.i: src/PartieDeclarative.cpp.i

.PHONY : src/PartieDeclarative.i

# target to preprocess a source file
src/PartieDeclarative.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/PartieDeclarative.cpp.i
.PHONY : src/PartieDeclarative.cpp.i

src/PartieDeclarative.s: src/PartieDeclarative.cpp.s

.PHONY : src/PartieDeclarative.s

# target to generate assembly for a file
src/PartieDeclarative.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/PartieDeclarative.cpp.s
.PHONY : src/PartieDeclarative.cpp.s

src/PartieInstruction.o: src/PartieInstruction.cpp.o

.PHONY : src/PartieInstruction.o

# target to build an object file
src/PartieInstruction.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/PartieInstruction.cpp.o
.PHONY : src/PartieInstruction.cpp.o

src/PartieInstruction.i: src/PartieInstruction.cpp.i

.PHONY : src/PartieInstruction.i

# target to preprocess a source file
src/PartieInstruction.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/PartieInstruction.cpp.i
.PHONY : src/PartieInstruction.cpp.i

src/PartieInstruction.s: src/PartieInstruction.cpp.s

.PHONY : src/PartieInstruction.s

# target to generate assembly for a file
src/PartieInstruction.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/PartieInstruction.cpp.s
.PHONY : src/PartieInstruction.cpp.s

src/Programme.o: src/Programme.cpp.o

.PHONY : src/Programme.o

# target to build an object file
src/Programme.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Programme.cpp.o
.PHONY : src/Programme.cpp.o

src/Programme.i: src/Programme.cpp.i

.PHONY : src/Programme.i

# target to preprocess a source file
src/Programme.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Programme.cpp.i
.PHONY : src/Programme.cpp.i

src/Programme.s: src/Programme.cpp.s

.PHONY : src/Programme.s

# target to generate assembly for a file
src/Programme.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/Programme.cpp.s
.PHONY : src/Programme.cpp.s

src/States/E0.o: src/States/E0.cpp.o

.PHONY : src/States/E0.o

# target to build an object file
src/States/E0.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/States/E0.cpp.o
.PHONY : src/States/E0.cpp.o

src/States/E0.i: src/States/E0.cpp.i

.PHONY : src/States/E0.i

# target to preprocess a source file
src/States/E0.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/States/E0.cpp.i
.PHONY : src/States/E0.cpp.i

src/States/E0.s: src/States/E0.cpp.s

.PHONY : src/States/E0.s

# target to generate assembly for a file
src/States/E0.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/States/E0.cpp.s
.PHONY : src/States/E0.cpp.s

src/States/E1.o: src/States/E1.cpp.o

.PHONY : src/States/E1.o

# target to build an object file
src/States/E1.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/States/E1.cpp.o
.PHONY : src/States/E1.cpp.o

src/States/E1.i: src/States/E1.cpp.i

.PHONY : src/States/E1.i

# target to preprocess a source file
src/States/E1.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/States/E1.cpp.i
.PHONY : src/States/E1.cpp.i

src/States/E1.s: src/States/E1.cpp.s

.PHONY : src/States/E1.s

# target to generate assembly for a file
src/States/E1.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/States/E1.cpp.s
.PHONY : src/States/E1.cpp.s

src/TestSymbolsClass.o: src/TestSymbolsClass.cpp.o

.PHONY : src/TestSymbolsClass.o

# target to build an object file
src/TestSymbolsClass.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/TestSymbolsClass.cpp.o
.PHONY : src/TestSymbolsClass.cpp.o

src/TestSymbolsClass.i: src/TestSymbolsClass.cpp.i

.PHONY : src/TestSymbolsClass.i

# target to preprocess a source file
src/TestSymbolsClass.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/TestSymbolsClass.cpp.i
.PHONY : src/TestSymbolsClass.cpp.i

src/TestSymbolsClass.s: src/TestSymbolsClass.cpp.s

.PHONY : src/TestSymbolsClass.s

# target to generate assembly for a file
src/TestSymbolsClass.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/TestSymbolsClass.cpp.s
.PHONY : src/TestSymbolsClass.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/lut.dir/build.make CMakeFiles/lut.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lut"
	@echo "... src/Affectation.o"
	@echo "... src/Affectation.i"
	@echo "... src/Affectation.s"
	@echo "... src/Automaton.o"
	@echo "... src/Automaton.i"
	@echo "... src/Automaton.s"
	@echo "... src/DeclarationConst.o"
	@echo "... src/DeclarationConst.i"
	@echo "... src/DeclarationConst.s"
	@echo "... src/DeclarationVariable.o"
	@echo "... src/DeclarationVariable.i"
	@echo "... src/DeclarationVariable.s"
	@echo "... src/Ecrire.o"
	@echo "... src/Ecrire.i"
	@echo "... src/Ecrire.s"
	@echo "... src/Expression.o"
	@echo "... src/Expression.i"
	@echo "... src/Expression.s"
	@echo "... src/Lexer.o"
	@echo "... src/Lexer.i"
	@echo "... src/Lexer.s"
	@echo "... src/Lire.o"
	@echo "... src/Lire.i"
	@echo "... src/Lire.s"
	@echo "... src/PartieDeclarative.o"
	@echo "... src/PartieDeclarative.i"
	@echo "... src/PartieDeclarative.s"
	@echo "... src/PartieInstruction.o"
	@echo "... src/PartieInstruction.i"
	@echo "... src/PartieInstruction.s"
	@echo "... src/Programme.o"
	@echo "... src/Programme.i"
	@echo "... src/Programme.s"
	@echo "... src/States/E0.o"
	@echo "... src/States/E0.i"
	@echo "... src/States/E0.s"
	@echo "... src/States/E1.o"
	@echo "... src/States/E1.i"
	@echo "... src/States/E1.s"
	@echo "... src/TestSymbolsClass.o"
	@echo "... src/TestSymbolsClass.i"
	@echo "... src/TestSymbolsClass.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

